### PR TITLE
01 fix less bar

### PR DESCRIPTION
**Pull request by lynndotconfig**

### CODE REVIEW

**Comment by lynndotconfig** [comment]
@elicoidal 
@uynil 
@siyuancn 
@seb-elico 
Please help me review the code.

**Comment by uynil** [comment]
change the src less file to build the js files successfully.

**Comment by uynil** [comment]
LGTM

**Comment by siyuancn** [comment]
LGTM

**Comment by lynndotconfig** [comment]
@elicoidal 
@uynil 
@siyuancn 
@seb-elico 
please help to merge,if you think it is good.

**Pull request merged**
