### PR TITLE
04 prepare hook for cas plugin

### PR DESCRIPTION
**Pull request by lynndotconfig**
- [add] fields in rainloop_users
- [add] hook filter.pre-do-login
- [add] hook service.after-logout

### CODE REVIEW

**Comment by lynndotconfig** [comment]
@elicoidal 
@uynil 
@seb-elico

**Comment by duanyp1991** [comment]
@seb-elico  @elicoidal   Please have a review and merge this PR, I dont have write access. thanks

**Comment by elicoidal** [comment]
Added reviewers (write) and Noah (Read) to the repo

**Comment by noahzaozao** [comment]
close the duplicated PRs

**Pull request closed without merging**
